## Valid Request

POST http://localhost:8081/api/user
Content-Type: application/json

{
  "userName": "doe",
  "email": "john.doe@testsubject.de",
  "firstName": "John",
  "lastName": "Doe",
  "password":"foobar"
}

###
## Invalid Request

POST http://localhost:8081/api/user
Content-Type: application/json

{
  "userName": "!!",
  "email": "john.doe@@@testsubject.de",
  "firstName": "John",
  "lastName": "Doe13",
  "password":"foobar"
}

###